name: super_tic_tac_toe
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cartoon-0.png
    - assets/images/cartoon-1.png
    - assets/images/cartoon-2.png
    - assets/images/cartoon-3.png
    - assets/images/cartoon-4.png
    - assets/images/cartoon-5.png
    - assets/images/cartoon-6.png
    - assets/images/cartoon-7.png
    - assets/images/cartoon-8.png
    - assets/images/cartoon-9.png
    - assets/images/cartoon-10.png
